profesea/new-profesea-fe

src/layouts/components/CandidateProfile.tsx
src/pages/candidate/DialogAddDocument.tsx

- fix spoken to language 
- enable set availabel to work 
- fix bug upload dokumen
- fix preview work experience and dokumen section

hotfix candidate profile missing done

---

src/contract/models/job.ts
src/pages/admin/accounts/AccountDatagrid.tsx
src/pages/admin/accounts/index.tsx
src/pages/candidate/find-job/index.tsx
src/pages/company/job-management/DialogAdd.tsx
src/pages/company/job-management/form/FormAddNonSeafarer.tsx
src/pages/company/job-management/form/FormAddSeafarer.tsx
yarn.lock

1.  update form add job company (Pelaut dan non Pelaut)
2. hide filter company
3. add new field registered_at in table list account

Improvement dais

---

src/configs/acl.ts
src/layouts/components/Registration.tsx
src/layouts/components/RegistrationEvent.tsx
src/navigation/horizontal/index.ts
src/navigation/vertical/index.ts
src/pages/admin/training-management-instant/settings/QuestionForm.tsx
src/pages/admin/training-management-instant/settings/QuestionPreview.tsx
src/pages/candidate/find-job/applied/index.tsx
src/pages/candidate/find-job/index.tsx
src/pages/candidate/job/index.tsx
src/pages/candidate/training/in-house/index.tsx
src/pages/candidate/training/index.tsx
src/pages/candidate/training/ongoing/index.tsx
src/pages/index.tsx
src/pages/register/event/[[...eventregister]].tsx
src/pages/register/index.tsx
src/pages/register/recruiter/index.tsx
src/pages/register/seafarer/index.tsx
src/pages/register/seafareroffship/index.tsx
src/pages/register/seafareronship/index.tsx
src/pages/register/trainer/index.tsx

- fix form autocomplete pelaut dan non pelaut 
- fix misspell seafarer file dan variable

fix form and misspell seafarer

---

src/pages/socialfeed/index.tsx

Improvement feed home page

---

src/layouts/components/CandidateProfile.tsx
src/layouts/components/DocumentUploadSection.tsx
src/layouts/components/EducationalInfoSection.tsx
src/layouts/components/WorkExperienceSection.tsx
src/pages/candidate/SeafarerCompetency/SeafarerCompetencyContainer.tsx
src/pages/candidate/SeafarerCompetency/SeafarerCompetencyForm.tsx
src/pages/candidate/SeafarerExperience/SeafarerExperienceContainer.tsx
src/pages/candidate/SeafarerExperience/SeafarerExperienceForm.tsx
src/pages/candidate/SeafarerProficiency/SeafarerProficiencyContainer.tsx
src/pages/candidate/SeafarerProficiency/SeafarerProficiencyForm.tsx
src/pages/candidate/SeafarerTravelDocument/SeafarerTravelDocumentContainer.tsx
src/pages/candidate/SeafarerTravelDocument/SeafarerTravelDocumentForm.tsx
src/pages/profile/Educational.tsx

Profile resume builder

---

src/pages/profile/Educational.tsx
src/pages/profile/ProfileFeedCard.tsx
src/pages/profile/[[...username]].tsx

- fix image on education 
- fix profile feed

Profile layout revamp

---

src/pages/company/job-management/form/FormAddNonSeafarer.tsx
src/pages/company/job-management/form/FormAddSeafarer.tsx

- fix form label contract 
- add arrow job rank

Fix form add job

---

src/pages/profile/[[...username]].tsx

- set employee_type == 'onship' for accessing table travel document and so on

set employee type

---

src/pages/profile/ProfileFeedCard.tsx
src/pages/profile/[[...username]].tsx

hide profile feed

---

src/layouts/components/CompanyProfile.tsx
src/layouts/components/ProfileViewerCard.tsx

updates link whos see your profile

Development merge to master

---

src/pages/candidate/job/CertificateDialog.tsx
src/pages/candidate/job/index.tsx
src/pages/job/[companyname]/[id]/[jobtitle]/index.tsx

fix build eslint

---

src/pages/candidate/DialogEditBanner.tsx

- fix bug on banner photo crop

fix bug banner photo crop

---

src/layouts/components/DocumentUploadSection.tsx
src/pages/candidate/DialogEditDocument.tsx

Document-Improvement

---

.env.development

Download upload document

---

src/contract/types/seafarer_recommendation_type.ts
src/layouts/components/CandidateProfile.tsx
src/layouts/components/SeafarerRecommendationTable.tsx
src/pages/candidate/SeafarerRecommendation/SeafarerRecommendationContainer.tsx
src/pages/candidate/SeafarerRecommendation/SeafarerRecommendationDeleteConfirm.tsx
src/pages/candidate/SeafarerRecommendation/SeafarerRecommendationForm.tsx
src/pages/company/DialogAddDocument.tsx

Recommendation improve

---

src/layouts/components/CandidateProfile.tsx
src/pages/candidate/DialogBannerDeleteConfirmation.tsx
src/pages/candidate/DialogEditBanner.tsx
src/pages/candidate/DialogEditProfile.tsx
src/pages/candidate/DialogProfileDeleteConfirmation.tsx

- crop photo profile and banner
- delete photo profile and banner

Photo dropdown menu

---

src/layouts/components/Profile.tsx
src/pages/profile/connections/DialogRemoveConnection.tsx
src/pages/profile/connections/index.tsx
src/utils/helpers.ts

build
```
Route (pages)                                                              Size     First Load JS
┌ ○ / (306 ms)                                                             13 kB          1.07 MB
├   └ css/09a6c8321e7bfbc2.css                                             793 B
├   /_app                                                                  0 B            1.03 MB
├ ○ /401                                                                   182 B          1.03 MB
├ ○ /404                                                                   797 B          1.03 MB
├ ○ /500                                                                   782 B          1.03 MB
├ ○ /account                                                               6.76 kB        1.04 MB
├   └ …
```

User data connection

---

src/layouts/components/CandidateProfile.tsx
src/layouts/components/CompanyProfile.tsx
src/pages/candidate/SeafarerRecommendation/SeafarerRecommendationContainer.tsx

```
├ ○ /thread/edit                                                           2.73 kB        1.11 MB
├ ○ /thread/Recomended                                                     2.98 kB        1.08 MB
├ ○ /thread/ShareArea                                                      2.54 kB        1.04 MB
├ ○ /trainer                                                               4.5 kB         1.06 MB
├ ○ /trainer/training                                                      1.92 kB         1.2 MB
├ ○ /trainer/training/all                                                  241 B          1.19 MB
├ ○ /trainer/training/all/DialogAdd                                        2.31 kB        1.11 MB
├ ○ /trainer/training/all/DialogDelete                                     1.65 kB        1.03 MB
├ ○ …
```

update mandatory field

---

package.json
src/context/BreadcrumbsNewsContext.tsx
src/layouts/components/FriendSuggestionCard.tsx
src/pages/_document.tsx
src/pages/news/HighlightedCardNews.tsx
src/pages/news/detail/[[...namanews]].tsx
src/pages/news/index.tsx
yarn.lock

- fix error 402 in friend suggestion list 
- fix error eslint to TS format standard 
- fix build 
```
Route (pages)                                                              Size     First Load JS
┌ ○ /                                                                      15.2 kB        1.07 MB
├   └ css/09a6c8321e7bfbc2.css                                             793 B
├   /_app                                                                  0 B            1.03 MB
├ ○ /401                                                                   182 B          1.03 MB
├ ○ /404                                                                   797 B          1.03 MB
├ ○ /500                                                                   782 B          1.03 MB
├ ○ /account …
```

fix bug in friend suggestion and fix error es lint

---

src/pages/candidate/SeafarerCompetency/SeafarerCompetencyForm.tsx
src/pages/candidate/SeafarerExperience/SeafarerExperienceForm.tsx
src/pages/candidate/SeafarerProficiency/SeafarerProficiencyForm.tsx
src/pages/candidate/SeafarerRecommendation/SeafarerRecommendationForm.tsx
src/pages/candidate/SeafarerTravelDocument/SeafarerTravelDocumentForm.tsx
yarn.lock

- fix reset after submit 
- build

fix reset form after submit

---

src/layouts/components/CandidateProfile.tsx
src/layouts/components/DocumentUploadSection.tsx
src/pages/candidate/DialogAddDocument.tsx
src/pages/candidate/DialogAddEducation.tsx
src/pages/candidate/DialogEditDocument.tsx
src/pages/candidate/DialogEditEducation.tsx

- change date format in date of birth 
- fix BASE URL preview file certificate 
- wording upload certificate

change date format, wording upload, base url preview file certificate

---

src/views/find-candidate/RecomendedViewTesting.tsx

testing acl issue (adding error handling when data is null)

Testing Acl Issue #7

---

src/contract/models/user.ts
src/views/social-feed/ButtonUploadPhoto.tsx
src/views/social-feed/ButtonUploadVideo.tsx
src/views/social-feed/Postfeed.tsx

Feat pop feeds policy

---

src/pages/admin/master-news/create/index.tsx
src/pages/news/detail/[[...namanews]].tsx
src/pages/news/index.tsx
styles/globals.css

fix issue repetition title at news page

fix issue repetition title at news page

---

src/pages/admin/master-news/edit/index.tsx

Hotfix repetition title

---

src/layouts/components/CandidateProfile.tsx
src/pages/profile/connections/CompanyListTab.tsx
src/pages/profile/connections/ConnectionTab.tsx
src/pages/profile/connections/RequestTab.tsx
src/pages/profile/connections/SuggestionTab.tsx
src/pages/profile/connections/index.tsx

sudah di fix untuk submit 
hanya , untuk pekerjaan si mike belum di update
kalau gak salah mengupdate label language

Fix submit candidate

---

src/pages/profile/connections/index.tsx

remove company tab

---

src/views/social-feed/ButtonRepost.tsx

Adding margin top in action repost

---

src/layouts/components/Registration.tsx
src/pages/register/recruiter/index.tsx
src/pages/register/seafarer/index.tsx
src/pages/register/seafareroffship/index.tsx
src/pages/register/seafareronship/index.tsx
src/pages/register/trainer/index.tsx

the email has been taken (because mikhailyuwankho@gmail.com is taken)

Fix register email not changing to lower case when submitted

---

src/layouts/components/ConnectButton.tsx
src/pages/profile/connections/ConnectionTab.tsx
src/pages/profile/connections/RequestTab.tsx
src/pages/profile/connections/SuggestionTab.tsx
src/pages/profile/connections/index.tsx
styles/css/ConnectionList.module.css
styles/css/ConnectionPage.module.css

Revamp connections fix figma design

---

src/pages/profile/[id]/[username]/index.tsx
src/views/profile/aboutMe.tsx
src/views/profile/activity.tsx
src/views/profile/cocSection.tsx
src/views/profile/copSection.tsx
src/views/profile/educationInfo.tsx
src/views/profile/profileHeader.tsx
src/views/profile/seafarerExperience.tsx
src/views/profile/seafarerTravelDocument.tsx

revisi ui di halaman new profile page
untuk button show more di cop dan coc section dibikin limit 3, jadi buttonnya bakal hilang kalau udh sama atau melebihi length dari data yang ada (visibleCount < data.length)

revisi ui di halaman new profile page

---

src/pages/profile/Certificate.tsx
src/pages/profile/Workexperience.tsx
src/pages/profile/[id]/[username]/index.tsx
src/pages/profile/index.tsx
src/views/profile/cocSection.tsx
src/views/profile/copSection.tsx
src/views/profile/profileHeader.tsx
src/views/profile/seafarerTravelDocument.tsx

Revamp profile page

---

src/pages/admin/company-and-job-management/index.tsx

add filter sort by

---

src/views/job-detail/SectionThreeJobDetal.tsx

improvement feature how you match

---

src/views/social-feed/CommentAreaView.tsx
src/views/social-feed/PopUpFeed.tsx
src/views/social-feed/Postfeed.tsx
src/views/social-feed/SubCommentAreaView.tsx

Popup Feed
Privacy Policy Translation

Add Translation in Privacy Policy Feed, Add Like & Comment Counter in Popup Feed and Remove Comment Created

---

src/layouts/components/ConnectButton.tsx
src/layouts/components/FriendSuggestionCard.tsx

Fix Connect Button and Friend Suggestion Layout

---

src/views/job-detail/SectionThreeJobDetal.tsx

Currently, Candidates who haven't logged in cannot access our job detail page.
(if job details require a license, the pages will redirect to the login page immediately)

Hotfix Issue Candidate Couldn't Open Job Detail Page

---

src/contract/models/role_type.ts
src/layouts/components/CandidateProfile.tsx
src/pages/admin/job-management/DialogEdit.tsx

update job title insert new

---

src/@core/styles/landing-page/landing-page-letssail.tsx
src/@core/theme/typography/index.ts
src/pages/candidate/job/index.tsx
src/pages/company/job/detail/index.tsx
src/pages/news/detail/[[...namanews]].tsx
src/pages/thread/index.tsx
src/utils/helpers.ts
src/views/alumni/CardAlumni.tsx
src/views/alumni/ListAlumni.tsx
src/views/alumni/ListAlumniContributor.tsx
src/views/alumni/ListAlumniLatter.tsx
src/views/alumni/ListAlumniLeft.tsx
src/views/alumni/ListAlumniTop.tsx
src/views/group/CardGroup.tsx
src/views/group/ListGroup.tsx
src/views/group/ListGroupLeft.tsx
src/views/job-detail/SectionTwoJobDetail.tsx
styles/globals.css

change font family from outfit to figtree

Change Global Font Family, and Related Files

---

package.json
src/pages/profile/Certificate.tsx
src/views/profile/cocSection.tsx
src/views/profile/copSection.tsx
src/views/profile/seafarerTravelDocument.tsx
src/views/social-feed/PostFeedDialog.tsx
src/views/social-feed/Postfeed.tsx
styles/scss/Dropzone.module.scss
yarn.lock

post feed dialog modal

---

src/views/landing-page/SuccessStoryView.tsx
src/views/landing-page/carouselevent.tsx
src/views/landing-page/footerView.tsx
src/views/landing-page/headerBannerView.tsx
src/views/landing-page/newsView.tsx
src/views/landing-page/ourBenefitView.tsx
src/views/landing-page/ourFeatureView.tsx
src/views/landing-page/ourPartnerView.tsx
src/views/landing-page/professionalPlatformView.tsx
src/views/landing-page/recruiterPlatformView.tsx
src/views/landing-page/sailOpportunityView.tsx
src/views/landing-page/seafarerPlatformView.tsx
src/views/landing-page/trainerPlatformView.tsx

changes mobile styling in landing page and adds more jobs button in the carousel event

Latest Changes Landing Page

---

src/@core/styles/landing-page/landing-page-letssail.tsx
src/views/landing-page/SuccessStoryView.tsx
src/views/landing-page/carouselevent.tsx
src/views/landing-page/headerBannerView.tsx
src/views/landing-page/ourBenefitView.tsx
src/views/landing-page/ourFeatureView.tsx
src/views/landing-page/professionalPlatformView.tsx
src/views/landing-page/recruiterPlatformView.tsx
src/views/landing-page/sailOpportunityView.tsx
src/views/landing-page/seafarerPlatformView.tsx
src/views/landing-page/trainerPlatformView.tsx

changes carousel, button and font size

Latest Changes in Landing Page

---

src/lang/en.json
src/lang/id.json
src/views/landing-page/ourPartnerView.tsx
src/views/landing-page/professionalPlatformView.tsx
src/views/landing-page/seafarerPlatformView.tsx

adding max width in partner logo
and add salary: to be discussed in job card

Hotfix partner logo and add hide salary

---

src/pages/_app.tsx
src/services/hotjar.tsx

add Hotjar for production
notes: add new env data
NEXT_PUBLIC_HOTJAR_ID=3830456

Add Hotjar for Production

---

src/pages/profile/Workexperience.tsx
src/views/social-feed/PostFeedDialog.tsx

fix modal post feed and work experience section

fix modal post feed and work experience section

---

src/views/social-feed/ImageListFeed.tsx

Fix Image height in feed, and add background color

---

src/views/social-feed/PostFeedDialog.tsx

Hotfix error handling post feed

Hotfix error handling post feed

---

src/pages/admin/company-and-job-management/detail/JobManagementDataGrid.tsx
src/pages/company/job-management/JobDatagrid.tsx
src/pages/company/job-management/index.tsx

add check inactive job to company management job

---

src/configs/acl.ts
src/pages/verify-email/index.tsx

add acl verify-email

---

src/views/admin/dashboard/CardUserStat.tsx
src/views/admin/dashboard/analytics/TopCategory.tsx
src/views/admin/dashboard/analytics/TopLastJob.tsx
src/views/admin/dashboard/analytics/TopPostCompany.tsx

User dashboard overview

---

src/layouts/components/onboarding/BasicInformationOne.tsx
src/layouts/components/onboarding/BasicInformationTwo.tsx
src/layouts/components/onboarding/EmployerBasicInformationOne.tsx

bug cannot proceed after clicking continue
country phone have different value

Hotfix bug basic information step 2 cannot continue and fix issue country phone

---

src/pages/admin/training-management/DialogView.tsx
src/pages/candidate/training/detail/OtherTraining.tsx
src/pages/candidate/trainings/[trainername]/[id]/[trainingtitle]/OtherTraining.tsx
src/pages/candidate/trainings/[trainername]/[id]/[trainingtitle]/index.tsx
src/pages/landingpage-trainer/detail/OtherTraining.tsx
src/pages/profile/Training.tsx
src/pages/trainings/[trainername]/[id]/[trainingtitle]/OtherTraining.tsx

Expired training handling

---

src/pages/profile/[id]/[username]/index.tsx
src/views/profile/seafarerExperience.tsx

update sorting documents , show more in sea experience

---

src/@core/layouts/components/shared-components/NotificationDropdown.tsx
src/@core/layouts/components/shared-components/NotificationItem.tsx
src/@core/layouts/components/shared-components/NotificationsType.ts
src/pages/notifications/NotificationItem.tsx
src/pages/notifications/StyleBadge.tsx
src/pages/notifications/buildNotifies.tsx

Fix width issue in notification dropdown

Fix notification dropdown

---

src/context/DashboardContext.tsx
src/contract/models/account.ts
src/contract/types/dashboard_context_type.ts
src/pages/admin/accounts/AccountDatagrid.tsx
src/pages/admin/accounts/index.tsx
src/pages/admin/index.tsx
src/views/admin/dashboard/CardCompletionPercentage.tsx

Revamp cp dashboard

---

src/pages/profile/[id]/[username]/index.tsx
src/views/profile/seafarerExperience.tsx

fix bug show more experience and show less experience

---

src/pages/admin/index.tsx
src/views/admin/dashboard/CardActiveAds.tsx
src/views/admin/dashboard/analytics/TopPostCompany.tsx

Fix ads height and margin issue in admin

---

src/pages/admin/accounts/index.tsx

Fix admin account null handling

---

src/pages/401.tsx
src/pages/500.tsx
src/pages/_error.tsx

Add _error.tsx page for default handling error in NextJS

Add Error handling page

---

src/pages/admin/accounts/DialogCalculateAllUserCP.tsx
src/pages/admin/accounts/index.tsx

adding query params type to endpoint

User calculation cp

---

src/pages/index.tsx
src/views/landing-page/ourBenefitView.tsx

- adding smoothscroll into about page

Scrollintoview about

---

src/views/social-feed/ImageSlider.tsx
src/views/social-feed/PopUpFeed.tsx

Hotfix Feed Mobile Display

---

src/context/JobContext.tsx
src/contract/types/job_context_type.ts
src/pages/candidate/find-job/applied/index.tsx
src/pages/candidate/find-job/archived/index.tsx
src/pages/candidate/find-job/index.tsx
src/pages/candidate/find-job/saved/index.tsx
src/pages/candidate/job/CompleteDialog.tsx
src/views/find-job/RecomendedView.tsx

Revamp job feature

---

src/pages/company/job-management/v2.tsx

when not apply filter, the filter became inactive

Fix status filter in job management

---

src/pages/connections/CompanyListTab.tsx

- update wording not follow any company

update wording not follow any company

---

src/views/job-management/form/ProfessionalJob.tsx

Change label from Remote to Work Type

---

src/views/profile/profileHeader.tsx

login sebagai company melihat company 
login sebagai user melihat company 
login sebagai company melihat user 
login sebagai user melihat user

Company follow tab

---

src/contract/models/news.ts
src/pages/admin/master-news/create/index.tsx
src/pages/admin/master-news2/create/index.tsx
src/pages/admin/master-news2/edit/index.tsx
src/pages/news/detail/[[...namanews]].tsx
src/pages/news/index.tsx

in bahasa indonesia :
in english
perhatikan tulisan in english di akhir 
karena gak ada title english untuk jaga - jaga di bikin default text seperti itu

News language

---

src/pages/candidate/job/[companyname]/[id]/[jobtitle]/index.tsx
src/pages/company/job-management/index.tsx
src/pages/find-job/OngoingJob.tsx
src/pages/job/[companyname]/[id]/[jobtitle]/index.tsx
src/utils/helpers.ts
src/views/find-job/RecomendedView.tsx
src/views/find-job/RelatedJobView.tsx
src/views/job-detail/HeaderJobDetail.tsx
src/views/job-detail/SectionOneJobDetail.tsx
src/views/job-management/DialogUpload.tsx
src/views/job-management/form/ProfessionalJob.tsx
src/views/job-management/form/SeafarerJob.tsx
src/views/landing-page/professionalPlatformView.tsx
src/views/landing-page/seafarerPlatformView.tsx

Add logic if company not verified
Add dialog to upload document

Hotfix job management verification, fix salary in job card and tooltip in create job

---

src/pages/candidate/find-job/applied/index.tsx
src/pages/candidate/find-job/saved/index.tsx
src/utils/helpers.ts
src/views/find-job/RecomendedView.tsx

improvement save job card

---

src/pages/company/job-management/index.tsx

Fix Issue Company can create jobs by only uploading document

Stengthen Logic Verification for Company in Job Management

---

src/pages/candidate/find-job/applied/index.tsx
src/pages/candidate/job/ShareArea.tsx
src/pages/candidate/job/applied/[id]/index.tsx

Improvement details job after applied

---

src/@core/layouts/components/vertical/navigation/VerticalNavGroup.tsx
src/@core/layouts/components/vertical/navigation/VerticalNavLink.tsx
src/navigation/vertical/index.ts

[Improvement] Change Navbar for mobile  view

---

package.json
src/@core/layouts/components/shared-components/LanguageDropdown.tsx
src/i18next.ts
src/views/job-management/candidate-list/StatusCard.tsx
yarn.lock

Now language wont change when user do a hard refresh.
Added new package : i18next-browser-languagedetector. 
Its basically an i18n plugin to detect user language in the browser. For more info: https://github.com/i18next/i18next-browser-languageDetector

[Issue] Translation state on landing page

---

src/i18next.ts

Fix: error when showing text the first time user opened the website.

fix: undetected lang

---

src/i18next.ts
src/pages/profile/[username]/index.tsx
src/pages/profile/index.tsx

Simplify url profile

---

src/views/job-management/candidate-list/Candidate.tsx
src/views/job-management/candidate-list/CandidateListTabs.tsx

before scroll (shadow):
after scroll (no shadow):

Add Left Shadow in row action in applicant management

---

src/pages/faqs/index.tsx
src/pages/job/[companyname]/[id]/[jobtitle]/index.tsx
src/pages/privacy/index.tsx
src/pages/term/index.tsx
src/pages/trainings/[trainername]/[id]/[trainingtitle]/index.tsx

Impacted pages:
- job details page
- training detail page
- /faqs
- /privacy
- /term

Hotfix change navbar to outer component navbar

---

src/layouts/components/CompanyProfile.tsx
src/pages/candidate/accordion-tab-general/FormPersonalData.tsx
src/pages/company/job-management/[id]/index.tsx
src/pages/company/job-management/index.tsx
src/pages/company/job/[id]/index.tsx
src/views/job-management/JobCard.tsx
src/views/job-management/candidate-list/CandidateListTabs.tsx
src/views/job-management/candidate-list/ProceedDialog.tsx
src/views/job-management/candidate-list/RejectDialog.tsx

Fix Job management issue
- search nggak jalan
- filter vessel type ilangin pas job professional
- next page nggak berfungsi
- not suitable ubah jadi Bahasa Indonesia
Improvement
- Add link di job name
- Implement new job detail page (company POV)
Edit profile issue
- gender required di company
- fix wording di trainer edit profile

Hotfix Job management issue and company profile

---

src/pages/candidate/DialogResumeBuilder.tsx
src/pages/candidate/job/CompleteDialog.tsx
styles/scss/Dropzone.module.scss

change some styles and fix some functionality

---

src/views/find-candidate/RecomendedView.tsx

Open chat function in find candidate

---

src/configs/acl.ts
src/navigation/horizontal/index.ts
src/navigation/vertical/index.ts
src/pages/candidate/trainings/[trainername]/[id]/[trainingtitle]/index.tsx
src/pages/candidate/trainings/index.tsx
src/pages/candidate/trainings/ongoing/index.tsx
src/pages/company/find-training/index.tsx
src/pages/company/trainings/[trainername]/[id]/[trainingtitle]/index.tsx
src/views/training-management/TrainingCard.tsx
src/views/training-management/admin/AdminComponent.tsx

open find training page and training detail page

Improvement: Open find training page to company user

---

src/pages/candidate/trainings/[trainername]/[id]/[trainingtitle]/index.tsx

add new description to explain terms and conditions

Hotfix add terms and condition in training page details

---

src/views/training-management/admin/AdminCandidate.tsx
src/views/training-management/admin/ChangeScheduleDialog.tsx

Add set schedule in admin pov

---

src/views/training-management/admin/AdminCandidate.tsx

Add new column: Enrollment type
and make PIC_name return between full name & pic name based on Enrollment type

Add new pic name and company name in participant list POV admin

---

src/pages/candidate/DialogAddWorkExperience.tsx
src/pages/candidate/DialogEditWorkExperience.tsx

Add logic that requires start date and turn to null if there is no start date

Hotfix form work experience

---

src/@core/layouts/components/shared-components/NotificationItem.tsx
src/layouts/components/UserProfileHeader.tsx
src/pages/company/job/applied/DialogView.tsx
src/pages/company/job/saved/AppliedDataGrid.tsx
src/pages/news/Commented.tsx
src/pages/notifications/NotificationItem.tsx
src/pages/profile/ProfileFeedCard.tsx
src/pages/thread/Commented.tsx
src/pages/thread/Recomended.tsx
src/pages/trainer/training/all/DialogViewParticipant.tsx
src/views/alumni/ListAlumniLeft.tsx
src/views/alumni/ListMember.tsx
src/views/appbar/appbar-search-user.tsx
src/views/community/ListThreadView.tsx
src/views/group/CardGroup.tsx
src/views/profile/activity.tsx
src/views/seeprofile/ListSeeProfile.tsx
src/views/social-feed/CommentAreaView.tsx
src/views/social-feed/CommentAreaViewAlumni.tsx
src/views/social-feed/CommentAreaViewGroup.tsx
src/views/social-feed/FeedCard.tsx
src/views/social-feed/FeedCardAlumni.tsx
src/views/social-feed/FeedCardGroup.tsx
src/views/social-feed/PopUpFeed.tsx
src/views/social-feed/SubCommentAreaView.tsx

remove id in href link simplify url

Hotfix url for service simplify url

---

src/pages/candidate/trainings/[trainername]/[id]/[trainingtitle]/index.tsx

Hide text banner (master)

---

src/layouts/components/Profile.tsx
src/pages/profile/Workexperience.tsx

fix direction url

---

src/context/TrainingContext.tsx
src/pages/trainings/OngoingTraining.tsx

Fix issue with fetching training on page /trainings

Hotfix flickering on loading and infinite looping issue

---

src/views/profile/postingSlider.tsx

fix error when open company profile

Add ternary operator

---

src/pages/candidate/find-job/archived/index.tsx

show job archive data list

---

.github/workflows/production-cd.yml

Remote host identification has changed issue

Add fingerprint in production-cd.yml

---

src/@core/layouts/components/landing-page-appbar/index.tsx
src/lang/en.json
src/lang/id.json

change navbar before login

---

src/pages/candidate/education-tab/FormEducation.tsx

fix: datepicker mobile issue when adding new education

---

src/@core/components/subscription/ModalUnlockPlus.tsx
src/@core/components/subscription/ModalUnlockPlusCandidate.tsx
src/contract/models/user.ts
src/pages/admin/feedback-management/free-trial-insight/index.tsx
src/pages/candidate/index.tsx
src/pages/candidate/job/CompleteDialog.tsx
src/pages/company/job-management/index.tsx
src/views/candidate/BoostCandidateAlert.tsx
src/views/find-candidate/RecomendedView.tsx
src/views/job-management/BoostJobAlert.tsx
src/views/job-management/form/ProfessionalJob.tsx
src/views/job-management/form/SeafarerJob.tsx

Hasil run build:
Desktop View:
Mobile View:
Note: Sekalian Fix:
1,Text di unlock modal
2.ga bisa subscribe

Improvement subs boosted recommendation

---

src/pages/admin/feedback-management/free-trial-insight/index.tsx
src/views/admin/feedback-management/TableUser.tsx

Hasil run build:
View tab candidate:

Candidate tab admin dashboard

---

src/contract/models/user.ts
src/views/find-candidate/RecomendedView.tsx

Hasil run build:
desktop view:
mobile view:

add: recommendation view in find-candidate

---

src/pages/candidate/trainings/[trainername]/[id]/[trainingtitle]/index.tsx
src/pages/candidate/trainings/ongoing/index.tsx
src/pages/trainings/OngoingTraining.tsx
src/pages/trainings/detail/[trainername]/[id]/[trainingtitle]/index.tsx
src/views/profile/posting.tsx
src/views/profile/postingSlider.tsx

Hotfix currency training card

---

src/pages/candidate/trainings/index.tsx
src/views/training/TrainingPartnerSection.tsx

adjust spacing and increase size logo image

---

src/pages/candidate/index.tsx
src/pages/company/index.tsx

fix issue vessel_type error and margin issue in edit profile page

Fix Error Page Job Detail when vessel_type is null

---

src/views/social-feed/ButtonLike.tsx
src/views/social-feed/CommentAreaView.tsx
src/views/social-feed/CommentAreaViewAlumni.tsx
src/views/social-feed/CommentAreaViewGroup.tsx
src/views/social-feed/FeedBottomActions.tsx
src/views/social-feed/SubCommentAreaView.tsx
src/views/social-feed/SubCommentAreaViewAlumni.tsx
src/views/social-feed/SubCommentAreaViewGroup.tsx

fix feeds bugs

---

src/context/CandidateContext.tsx
src/contract/types/candidate_context_type.ts
src/pages/company/find-candidate/index.tsx

Feat ave candidate

---

src/@core/layouts/components/shared-components/NotificationDropdown.tsx
src/@core/layouts/components/shared-components/NotificationItem.tsx
src/contract/types/notification_type.ts
src/pages/notifications/NotificationItem.tsx
src/pages/notifications/buildNotifies.tsx
src/pages/notifications/index.tsx

build 
sebagai aries dimas , comment di feed aquamarine tidak mendapat notif 
sebagai aquamarine , mendapatkan notif 
comment ke-2 , gak dapet notif

add notification first comment

---

src/@core/components/custom-tabs/index.tsx
src/@core/components/subscription/CandidatePlanComparison.tsx
src/@core/layouts/AccountLayout.tsx
src/@core/layouts/components/shared-components/UserDropdown.tsx
src/layouts/components/ChangePassword.tsx
src/pages/account/index.tsx
src/pages/account/my-account.tsx
src/pages/account/my-training/[orderId].tsx
src/pages/account/my-training/index.tsx
src/pages/account/subscription.tsx
src/utils/helpers.ts

- Run build test
- Revamp Dropdown Menu
- New Account Page

New Feature Account Page

---

src/context/JobContext.tsx
src/contract/types/job_context_type.ts
src/pages/candidate/find-job/index.tsx

Fix Sort in find-job Page

---

src/pages/admin/accounts/AccountDatagrid.tsx
src/pages/admin/accounts/index.tsx

build
button for recalculate user

add calculation per user

---

src/lang/en.json
src/lang/id.json
src/pages/employer/pricing/index.tsx

change icon and wording

---

src/views/job-detail/JobDetailSection.tsx

Fix: hide salary

---

src/views/landing-page/professionalPlatformView.tsx

- npm run build
- changes job card

Hotfix Landing Page Professional Job Card

---

src/context/CandidateContext.tsx
src/contract/models/job.ts
src/contract/types/create_job_type.ts
src/pages/admin/job-management/DialogEdit.tsx
src/pages/admin/job-management/form/FormAddNonSeafarer.tsx
src/pages/admin/job-management/form/FormAddSeafarer.tsx
src/pages/company/job-management/form/FormAddNonSeafarer.tsx
src/pages/company/job-management/form/FormAddSeafarer.tsx
src/views/job-management/form/ProfessionalJob.tsx
src/views/job-management/form/SeafarerJob.tsx

Payment periode job

---

src/pages/community/index.tsx
src/views/community/CommunityDetail.tsx
src/views/community/CommunityDetailSkeleton.tsx
src/views/community/CommunityMembersSection.tsx
src/views/community/DiscoverAndYourGroupsCommunity.tsx

Revamp community page

---

src/views/social-feed/ButtonDelete.tsx
src/views/social-feed/ButtonSettings.tsx

Fix Error Delete Feed

---

src/@core/layouts/LandingPageLayout.tsx
src/pages/admin/community-management/[id]/index.tsx
src/pages/admin/community-management/index.tsx
src/pages/community/index.tsx
src/views/community/CommunityDetail.tsx
src/views/community/CommunityEdit.tsx

add: community management

---

src/pages/profile/[username]/index.tsx
src/views/profile/activity.tsx

- npm run build
- Fix render image and video on user profile activity

Fix Issue Fetching Profile & Fix Feeds Activity

---

src/pages/notifications/NotificationItem.tsx
src/pages/notifications/buildNotifies.tsx
src/pages/notifications/index.tsx
src/views/social-feed/PostFeedDialog.tsx

fix: ga bisa post
